the_weather/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('weather_app.urls')),
]

weather_app/urls.py
from django.urls import path
from .views import index

app_name = 'weather_app'

urlpatterns = [
    path('', index, name='index-page')
]

weather_app/models.py
from django.db import models

class City(models.Model):
    name = models.CharField(max_length=25)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'cities'

weather_app/views.py
import requests
from django.shortcuts import render
from .models import City


def index(request):
    url = ' http://api.openweathermap.org/data/2.5/weather?q={}&units=metric&appid=45fb2035cf13c4adfd3f6a6dc978fad3'
    city = 'Dhaka'

    if request.method == 'POST':
        city = request.POST.get('data')

    r = requests.get(url.format(city)).json()
    
    if r['cod'] == '404':
        context = {
            'city': request.POST.get('data')
        }
        return render(request, 'weather_app/error.html', context)
    

    city_weather = {
        'city' : city,
        'temperature': r['main']['temp'],
        'description': r['weather'][0]['description'],
        'icon': r['weather'][0]['icon'] 
    }


    context = {
        'city': city_weather
    }
    
    return render(request, 'weather_app/weather.html', context)

templates/weather_app/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Opps!</title>
</head>
<body>
    <h2>{{ city }} does not exist on planet Earth!!</h2>
    <p><a href="{% url 'weather_app:index-page' %}">Go back</a> and retry with another city/country!</p>
</body>
</html>

templates/weather_app/weather.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Weather By Cities</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.2/css/bulma.css" />
</head>

<body>
    <section class="hero is-primary">
        <div class="hero-body">
            <div class="container">
                <h1 class="title">
                    What's the weather like at {{ city.city }}?
                </h1>
            </div>
        </div>
    </section>
    <section class="section">
        <div class="container">
            <div class="columns">
                <div class="column is-offset-4 is-4">
                    <form method="POST">{% csrf_token %}
                        <div class="field has-addons">
                            <div class="control is-expanded">
                                <input class="input" type="text" placeholder="City Name" name="data">
                            </div>
                            <div class="control">
                                <button class="button is-info" type="submit">
                                    Search City
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <section class="section">
        <div class="container">
            <div class="columns">
                <div class="column is-offset-4 is-4">
                    <div class="box">
                        <article class="media">
                            <div class="media-left">
                                <figure class="image is-50x50">
                                    <img src="http://openweathermap.org/img/w/{{ city.icon }}.png" alt="Image">
                                </figure>
                            </div>
                            <div class="media-content">
                                <div class="content">
                                    <p>
                                        <span class="title">{{ city.city }}</span>
                                        <br>
                                        <span class="subtitle">{{ city.temperature }}° C</span>
                                        <br> {{ city.description }}
                                    </p>
                                </div>
                            </div>
                        </article>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <footer class="footer">
    </footer>
</body>

</html>